package proj;

public enum TokenType {
    INT, ADD_OP, MINUS_OP, END_OF_FILE, SEMI, L_PAREN, R_PAREN, ASSIGN, IDENT, DIV, MULT, PERIOD, DIGIT, LETTER,
    UNKNOWN, KEYWORD, UNDERSCORE, AND, ARRAY, BEGIN, CASE, CONSTANT, DO, ELSE, END, FILE, FOR, FUNCTION, GOTO, IF, IN,
    MOD, NOT, OF, OR, PROCEDURE, RECORD, THEN, TYPE, UNTIL, WHILE, WITH, IS, DECLARE, NULL
}